{
	"version": 1726972813,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/loadingpinga-sheet0.png",
		"images/fundo1.png",
		"images/fundo2.png",
		"images/logobizarra-sheet0.png",
		"images/botões-sheet0.png",
		"images/botões-sheet1.png",
		"images/botões-sheet2.png",
		"images/botões-sheet3.png",
		"images/botões-sheet4.png",
		"images/botões-sheet5.png",
		"images/botões-sheet6.png",
		"images/botões-sheet7.png",
		"images/botões-sheet8.png",
		"images/botões-sheet9.png",
		"images/botões-sheet10.png",
		"images/botões-sheet11.png",
		"images/botões-sheet12.png",
		"images/botões-sheet13.png",
		"images/botões-sheet14.png",
		"images/botões-sheet15.png",
		"images/botões-sheet16.png",
		"images/botões-sheet17.png",
		"images/botões-sheet18.png",
		"images/botões-sheet19.png",
		"images/botões-sheet20.png",
		"images/botões-sheet21.png",
		"images/botões-sheet22.png",
		"images/botões-sheet23.png",
		"images/botões-sheet24.png",
		"images/botões-sheet25.png",
		"images/botões-sheet26.png",
		"images/botões-sheet27.png",
		"images/botões-sheet28.png",
		"images/botões-sheet29.png",
		"images/fonte1.png",
		"images/fontegrande1.png",
		"images/botaoir-sheet0.png",
		"images/fundo3.png",
		"images/transitionbar-sheet0.png",
		"images/downloadablepng-sheet0.png",
		"images/transitionback-sheet0.png",
		"images/processingload-sheet0.png",
		"images/processingload-sheet1.png",
		"images/transitionicon-sheet0.png",
		"images/transitionicon-sheet1.png",
		"images/fundo4.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground2.png",
		"images/buttonquick-sheet0.png",
		"media/main menu mode select - mario kart wii music extended.m4a",
		"media/main menu mode select - mario kart wii music extended.ogg",
		"media/main menu character and kart select - mario kart wii music extended.m4a",
		"media/main menu character and kart select - mario kart wii music extended.ogg",
		"media/main menu course select - mario kart wii music extended.m4a",
		"media/main menu course select - mario kart wii music extended.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"resolutionwarning.png"
	]
}